### ISSUE TITLE
TrendFiltering Doesn't Run

### ISSUE THREAD

**Issue by bubblesort251** [MTG1991/Trend-Filtering#1]
Hey, the ipython notebook doesn't run on my computer, it has issues with running the CVX implementation.  Is that what I am supposed to work on?

Please let me know.  I'll try and make the CVX implementation work on my machine tomorrow morning.

**Comment by MTG1991** [comment]
Thanks for working on the codes! Which version of CVXPY are you using? Looks like you need 1.0 or higher.

**Comment by bubblesort251** [comment]
I tried to update my cvxpy, but it won't update past 0.4.8.  Where can I find the most recent version?

### Update: I got it to work

**Comment by MTG1991** [comment]
There are instructions on the official website, though I remembered that you may need to update NumPy/scipy also...

Best,
Han
